[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ventaxia_ha"
version = "0.1.6"
description = "Home Assistant integration for VentAxia IoT devices"
authors = [{name = "josyban"}]
dependencies = ["ventaxiaiot>=0.1.7"]
